name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Install allure commandline
      run: npm install -g allure-commandline
    - name: Run report
      run: allure generate --clean   
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
